[package]
name = "littensy/reflex"
description = "A state container built for Roblox"
version = "4.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
	"src",
	"src/**",
	"default.project.json",
	"wally.toml",
	"LICENSE.md",
	"README.md",
]

[dependencies]
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
